### ISSUE TITLE
Add bbop.min.js to NPM

### ISSUE THREAD

**Issue by kshefchek** [berkeleybop/bbop-js#37]
I am unaware of the best practice of supplying minified js files for libraries that may be used on the client, but this would be useful for Monarch while we implement bundling of js and css files.

**Comment by kltm** [comment]
@kshefchek , all issues need cause, context, and description--no empty bodies allowed.

**Comment by kltm** [comment]
There should be no need to supply bbop.min.js as any downstream use will do their own bundling and minifying, etc.

**Comment by kshefchek** [comment]
@kltm I am new to npm, but other major libraries seem to provide this, such as jQuery and Underscore.js.  But this also something we could do on the app side of things.

**Comment by kltm** [comment]
Yes, to some extent you're correct. However, in the case of jQuery, it's a large piece meant to be a standalone library that you use to write your code with; this is also true, to a lesser extent, with underscore. In the case of bbop-js and family, they are more at the application library end--you write your application, with tons of other libraries, then compress (or not) as needed. Personally, I like to be able to get through my code--all code--uncompressed during development (yes, yes maps, etc.), then compress for "production".

I guess, to turn it around, what is the use case for pre-compression (and, I assume, map generation)?
